### ISSUE TITLE
add more exif tags

### ISSUE THREAD

**Issue by ghost** [k0rmarun/exiffind#1]
Please add some more exif tags like:
-width
-height
-camera model
-camera manufacturer
-some camera parameters (ISO, Av, etc)

Maybe it is also possible to search by ranges?
For example pictures _between_ 400x400 and 800x800?

Thx!

**Comment by k0rmarun** [comment]
Added parameters for :
- manufacturer
- model
- ISO value
- exposure
- aperature
- fnumber
- resolution (X/Y)

Improved range evaluation

See: https://github.com/k0rmarun/exiffind/pull/2/commits
